image: python:3.11

before_script:
  - pip install poetry

stages:
  - build
  - test

build:
  stage: build
  script:
    - poetry install --with dev

test:
  stage: test
  script:
    - poetry run pytest --version  # Проверяем наличие pytest
    - poetry run pytest
