image: python:3.11

before_script:
  - pip install --upgrade pip  # Обновляем pip до последней версии
  - pip install poetry

stages:
  - build
  - test

build:
  stage: build
  script:
    - poetry install --with dev

test:
  stage: test
  script:
    - poetry install --with dev  # Повторная установка (если это отдельный runner)
    - poetry run pytest --version  # Проверяем наличие pytest
    - poetry run pytest hello_world/tests  # Запуск тестов
