image: python:3.11

before_script:
  - pip install poetry

stages:
  - build
  - test

build:
  stage: build
  script:
    - poetry install --with dev  # Устанавливаем dev-зависимости

test:
  stage: test
  script:
    - poetry run pytest
